Programming/movement
RSGameDev/BeatsPerDeath pull request #6
Opened 2020-11-30 21:52 UTC by RSGameDev

Here's what i've done up to this evening. 
I tried amending the scripts i worked on so it adopts the preferred code style for this project.

I still would like to make a little bit more alteration to the movement code but I wanted to push an update so you have what  has been worked on currently.

The movement has been focused on. Now there is lerping, a couple of things that worked ok before aren't working as well now. This is mainly player-enemy interaction for example. Sometimes when the player goes into the enemy it stays on the same tile as the enemy instead of being pushed back. This is to do with the new lerp feature thats in the game.
So that's something we'll have to address at some point.

2020-12-03 16:06 UTC, KEREMADALI requested changes
Since it is a new convention for you, it is normal to mistake for some of them, please dont be discoured by my comments. As a reminder;

public  -> PascalCase
private -> _camelCase
local variable -> camelCase
Always define accessors both on variables and methods

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Floor/TileController.cs
> +    public bool tilesScrolling;
IsPlatformMoving is a better name and make it private if it doesn't have to be public, in that case _isPlatformMoving

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Floor/TileController.cs
> +    Vector3 tileMovement;
Please specify accessor and rename to _tileMovement

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Floor/TileController.cs
> +        distance = 1.25f;
Please make 1.25f a constant

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Floor/TileController.cs
> +                tileMovement = direction * (Time.deltaTime * (distance / 3f));
Please make 3f a constant

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Lose Condition/BottomRowHazard.cs
> +            //other.GetComponent<Player>().StartPosition();
Delete if unnecessary

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Mechanics/Anchor.cs
> +    Vector3 newPos;
please specify accessor and rename to _newPosition

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Mechanics/Anchor.cs
>      private void OnTriggerEnter(Collider other)
This method does too much job inside please seperate its responsilibities into smaller methods and make easy to read. It is impossible to understand what happens onTrigger

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/Player.cs
> +    #region Private variables
Great :)

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/Player.cs
> +    public bool isAlive = true;
PascalCase -> IsAlive

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/Player.cs
> +    public Vector3 startPos;
StartPosition

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/Player.cs
> +    public GameObject[] spawnPlayerDetect;
Please find a more definitive name

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/Player.cs
>      public GameUI gameUIScript;
Please use PascalCase on public variables

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/Player.cs
> +        _playerMovement = GetComponent<PlayerMovement>();
Add requiredComponent at the top of class

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/Player.cs
>      public void PlayerDied()
KillPlayer()

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/Player.cs
> +    IEnumerator EnableMove()
please specifty accessor

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/PlayerMovement.cs
> +    void Movement()
please specift accessor

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/PlayerMovement.cs
> +    void CheckBoundaries()
Accessor

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/PlayerMovement.cs
> +    void CheckBoundaries()
Please remove magic numbers in this method and add comments to this method

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/enemy/Enemy.cs
> +    public bool isNew = true;
IsPushBack, IsAlive, IsNew

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/enemy/Enemy.cs
>      private void EnemyDies()
KillEnemy();

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/enemy/EnemyMovement.cs
> +        _enemy = GetComponent<Enemy>();
Use requeiredocmponent

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/enemy/EnemyMovement.cs
> +            Lerp();
Make your code readable for anyone not for only coders. Assume that I dont know how to code. Lerp is a mystery for me, please use a more self explanatory method name

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/enemy/EnemyMovement.cs
> +    public bool lerp;
What is the usage of this boolean, name does not explain

2020-12-03 16:06 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/enemy/EnemyMovement.cs
> +        if (_enemy.currentEnemyType == Enemy.EnemyType.Rook)
An enemy cant be both rook and a shroom therfore use switch or if else

2020-12-04 16:11 UTC, RSGameDev reviewed
Hi, I'll push the changes shortly. Will mark for review again.

2020-12-04 16:19 UTC, RSGameDev reviewed
Hi, this is a recent push with code review changes based from the last review.
Let me know if it appears better. Thanks Kerem.

2020-12-08 23:17 UTC, closed without merging

2020-12-13 18:17 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Floor/TileController.cs
> +        if (SceneController.Instance.scrollBeatCount >= s_beatToStartScroll)
All of code in here seems like they control the same thing u can create a method for this and that method in Update

2020-12-13 18:28 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Mechanics/Anchor.cs
> +            print("fsavda");
Please remove

2020-12-13 18:30 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Mechanics/Anchor.cs
>      private void OnTriggerEnter(Collider other)
Good updates, you can add comments like resolved on fixes

2020-12-13 18:32 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/Player/PlayerMovement.cs
> +            IsLerpingStarted = false;
If we removede lerp can this bool deleted?

2020-12-13 18:35 UTC, KEREMADALI commented on bpdv3/Assets/Scripts/enemy/EnemyNextMove.cs
>      public bool CanMove()
CanEnemyMove is a better name for this method if it is being used by only the enemy

2020-12-13 18:36 UTC, KEREMADALI reviewed
Good updates well done

2020-12-13 18:39 UTC, RSGameDev commented
Thanks for the further comments, ill look at them fully over next couple days and will amend the code accordingly from the notes u have left. I'll look to make the shroom movement better working also as at the moment. It's not in the best shape ^^. Is getting there :).

2020-12-18 15:58 UTC, RSGameDev commented
Corrected. i forgot in a recent push but have done it for the push im about to do. Thanks for the review also.